/* automatically generated by rust-bindgen 0.73.2 */

pub const RYZENADJ_REVISION_VER: u32 = 0;
pub const RYZENADJ_MAJOR_VER: u32 = 19;
pub const RYZENADJ_MINIOR_VER: u32 = 0;
pub const ADJ_ERR_FAM_UNSUPPORTED: i32 = -1;
pub const ADJ_ERR_SMU_TIMEOUT: i32 = -2;
pub const ADJ_ERR_SMU_UNSUPPORTED: i32 = -3;
pub const ADJ_ERR_SMU_REJECTED: i32 = -4;
pub const ADJ_ERR_MEMORY_ACCESS: i32 = -5;
pub const ryzen_family_WAIT_FOR_LOAD: ryzen_family = -2;
pub const ryzen_family_FAM_UNKNOWN: ryzen_family = -1;
pub const ryzen_family_FAM_RAVEN: ryzen_family = 0;
pub const ryzen_family_FAM_PICASSO: ryzen_family = 1;
pub const ryzen_family_FAM_RENOIR: ryzen_family = 2;
pub const ryzen_family_FAM_CEZANNE: ryzen_family = 3;
pub const ryzen_family_FAM_DALI: ryzen_family = 4;
pub const ryzen_family_FAM_LUCIENNE: ryzen_family = 5;
pub const ryzen_family_FAM_VANGOGH: ryzen_family = 6;
pub const ryzen_family_FAM_REMBRANDT: ryzen_family = 7;
pub const ryzen_family_FAM_MENDOCINO: ryzen_family = 8;
pub const ryzen_family_FAM_PHOENIX: ryzen_family = 9;
pub const ryzen_family_FAM_HAWKPOINT: ryzen_family = 10;
pub const ryzen_family_FAM_DRAGONRANGE: ryzen_family = 11;
pub const ryzen_family_FAM_KRACKANPOINT: ryzen_family = 12;
pub const ryzen_family_FAM_STRIXPOINT: ryzen_family = 13;
pub const ryzen_family_FAM_STRIXHALO: ryzen_family = 14;
pub const ryzen_family_FAM_FIRERANGE: ryzen_family = 15;
pub const ryzen_family_FAM_END: ryzen_family = 16;
pub type ryzen_family = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug)]
pub struct _ryzen_access {
    _unused: [u8; 0],
}
pub type ryzen_access = *mut _ryzen_access;
unsafe extern "C" {
    pub fn init_ryzenadj() -> ryzen_access;
}
unsafe extern "C" {
    pub fn cleanup_ryzenadj(ry: ryzen_access);
}
unsafe extern "C" {
    pub fn get_cpu_family(ry: ryzen_access) -> ryzen_family;
}
unsafe extern "C" {
    pub fn get_bios_if_ver(ry: ryzen_access) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn init_table(ry: ryzen_access) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn get_table_ver(ry: ryzen_access) -> u32;
}
unsafe extern "C" {
    pub fn get_table_size(ry: ryzen_access) -> usize;
}
unsafe extern "C" {
    pub fn get_table_values(ry: ryzen_access) -> *mut f32;
}
unsafe extern "C" {
    pub fn refresh_table(ry: ryzen_access) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_stapm_limit(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_fast_limit(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_slow_limit(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_slow_time(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_stapm_time(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_tctl_temp(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_vrm_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_vrmsoc_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_vrmgfx_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_vrmcvip_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_vrmmax_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_vrmgfxmax_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_vrmsocmax_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_psi0_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_psi3cpu_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_psi0soc_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_psi3gfx_current(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_max_gfxclk_freq(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_min_gfxclk_freq(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_max_socclk_freq(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_min_socclk_freq(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_max_fclk_freq(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_min_fclk_freq(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_max_vcn(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_min_vcn(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_max_lclk(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_min_lclk(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_prochot_deassertion_ramp(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_apu_skin_temp_limit(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_dgpu_skin_temp_limit(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_apu_slow_limit(arg1: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_skin_temp_power_limit(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_gfx_clk(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_oc_clk(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_per_core_oc_clk(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_oc_volt(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_disable_oc(ry: ryzen_access) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_enable_oc(ry: ryzen_access) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_power_saving(ry: ryzen_access) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_max_performance(ry: ryzen_access) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_coall(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_coper(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_cogfx(ry: ryzen_access, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn get_stapm_limit(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_stapm_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_fast_limit(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_fast_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_slow_limit(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_slow_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_apu_slow_limit(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_apu_slow_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrm_current(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrm_current_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrmsoc_current(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrmsoc_current_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrmmax_current(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrmmax_current_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrmsocmax_current(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_vrmsocmax_current_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_tctl_temp(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_tctl_temp_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_apu_skin_temp_limit(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_apu_skin_temp_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_dgpu_skin_temp_limit(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_dgpu_skin_temp_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_psi0_current(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_psi0soc_current(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_stapm_time(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_slow_time(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_cclk_setpoint(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_cclk_busy_value(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_core_clk(ry: ryzen_access, value: u32) -> f32;
}
unsafe extern "C" {
    pub fn get_core_volt(ry: ryzen_access, value: u32) -> f32;
}
unsafe extern "C" {
    pub fn get_core_power(ry: ryzen_access, value: u32) -> f32;
}
unsafe extern "C" {
    pub fn get_core_temp(ry: ryzen_access, value: u32) -> f32;
}
unsafe extern "C" {
    pub fn get_l3_clk(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_l3_logic(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_l3_vddm(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_l3_temp(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_gfx_clk(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_gfx_temp(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_gfx_volt(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_mem_clk(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_fclk(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_soc_power(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_soc_volt(ry: ryzen_access) -> f32;
}
unsafe extern "C" {
    pub fn get_socket_power(ry: ryzen_access) -> f32;
}
